[package]
name = "runner"
version = "0.1.0"
authors = ["noiseOnTheNet <marco.p.v.vezzoli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "runner"
path = "main.rs"
